<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="lidar_link">
        <visual>
            <geometry>
                <box size="0.01 0.1 0.1"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.01 0.1 0.1"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="${(base_length + 0.01)/2} -0.15 0.2" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <gazebo reference="lidar_link">
        <sensor name="lidar_sensor" type="ray">
            <update_rate>30.0</update_rate>
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <ray>
                <scan>
                    <horizontal>
                        <samples>1080</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.5708</min_angle>
                        <max_angle>1.5708</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>lidar_link</frameName>
            </plugin>
        </sensor>
    </gazebo>
</robot>
