<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<link name="camera_link">
		<visual>
			<geometry>
				<box size="0.01 0.1 0.1"/>
			</geometry>
			<material name="grey"/>
		</visual>
		<collision>
			<geometry>
				<box size="0.01 0.1 0.1"/>
			</geometry>
		</collision>
		<xacro:box_inertia m="0.1" l="0.01" w="0.1" h="0.1" xyz="0 0 0" rpy="0 0 0"/>
	</link>

	<joint name="camera_joint" type="fixed">
		<parent link="base_link"/>
		<child link="camera_link"/>
		<origin xyz="${(base_length + 0.01)/2} 0.15 0.2" rpy="0.0 0.0 0.0"/>
	</joint>

	<gazebo reference="camera_link">
		<material>Gazebo/Pink</material>
		<sensor name="camera_sensor" type="camera">
			<pose>0 0 0 0 0 0</pose>		
			<visualize>true</visualize>
			<update_rate>30.0</update_rate>
			<camera name="camera">
				<horizontal_fov>1.047198</horizontal_fov>
				<image>
					<width>1280</width>
					<height>720</height>
					<format>R8G8B8</format>
				</image>
				<clip>
					<near>0.05</near>
					<far>20</far>
				</clip>
			</camera>
			<plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
				<baseline>0.2</baseline>
				<alwaysOn>true</alwaysOn>
				<updateRate>0.0</updateRate>
				<frame_name>camera_depth_frame</frame_name>
				<pointCloudCutoff>0.5</pointCloudCutoff>
				<pointCloudCutoffMax>3.0</pointCloudCutoffMax>
				<distortionK1>0</distortionK1>
				<distortionK2>0</distortionK2>
				<distortionK3>0</distortionK3>
				<distortionT1>0</distortionT1>
				<distortionT2>0</distortionT2>
				<CxPrime>0</CxPrime>
				<Cx>0</Cx>
				<Cy>0</Cy>
				<focalLength>0</focalLength>
				<hackBaseline>0</hackBaseline>
			</plugin>
		</sensor>
	</gazebo>
</robot>
